
CREATE TABLE USUARIO(
IDUSUARIO SERIAL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
CONTRA VARCHAR(50) NOT NULL,
NOMUSUARIO VARCHAR(50) NOT NULL,
NICK VARCHAR(50) NOT NULL
);

CREATE TABLE HABILIDAD(
IDHABILIDAD SERIAL PRIMARY KEY,
NOMBREHABILIDAD VARCHAR(50) NOT NULL,
CANTKARMA INT(50) NOT NULL
);

CREATE TABLE CONOCIMIENTO(
IDCONOCIMIENTO SERIAL PRIMARY KEY,
IDHABILIDAD BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDHABILIDAD) 
REFERENCES HABILIDAD(IDHABILIDAD),
IDUSUARIO BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDUSUARIO) 
REFERENCES USUARIO(IDUSUARIO),
NOMBRECONOCIMIENTO VARCHAR(50) NOT NULL,
CANTKARMA INT(50) NOT NULL
);

CREATE TABLE LISTACONTACTO(
IDLISTA SERIAL PRIMARY KEY,
IDUSUARIO BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDUSUARIO)
REFERENCES USUARIO(IDUSUARIO),
IDCONTACTO BIGINT NOT NULL
);

CREATE TABLE PUBLICACION(
IDPUBLICACION SERIAL PRIMARY KEY,
IDUSUARIO BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDUSUARIO)
REFERENCES USUARIO(IDUSUARIO),
PUBLICACION VARCHAR(200) NOT NULL,
FECHA DATE
);

CREATE TABLE QUEJA(
IDQUEJA SERIAL PRIMARY KEY,
IDPUBLICACION BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDPUBLICACION)
REFERENCES PUBLICACION(IDPUBLICACION),
DESCRIPCION VARCHAR(200) NOT NULL
);

CREATE TABLE ASOCIACION(
IDASOCIACION SERIAL PRIMARY KEY,
IDUSUARIO BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDUSUARIO)
REFERENCES USUARIO(IDUSUARIO),
ADMINISTRADOR BIGINT NOT NULL
);

CREATE TABLE MIEMBRO(
IDMIEMBRO SERIAL PRIMARY KEY,
IDASOCIACION BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDASOCIACION)
REFERENCES ASOCIACION(IDASOCIACION)
);

CREATE TABLE PROYECTO(
IDPROYECTO SERIAL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
FECHAINICIO DATE NOT NULL,
FECHAFIN DATE NOT NULL,
PRECIO INT NOT NULL
);

CREATE TABLE TAREA(
IDTAREA SERIAL PRIMARY KEY,
IDPROYECTO BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDPROYECTO)
REFERENCES PROYECTO(IDPROYECTO),
NOMBRETAREA VARCHAR(30) NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL,
ESTADO VARCHAR(30) NOT NULL,
FECHAINICIO DATE NOT NULL,
FECHAFIN DATE NOT NULL,
PRECIO INT NOT NULL
);

CREATE TABLE CONOTAREA(
IDCONOTAREA SERIAL PRIMARY KEY,
IDTAREA BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDTAREA)
REFERENCES TAREA(IDTAREA),
CONOCIMIENTOS VARCHAR(100) NOT NULL
);

CREATE TABLE PAGO(
IDPAGO SERIAL PRIMARY KEY,
IDTAREA BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDTAREA)
REFERENCES TAREA(IDTAREA),
FECHAPAGO DATE NOT NULL
);

CREATE TABLE ASIGNATAREA(
IDASIGNATAREA SERIAL PRIMARY KEY,
IDUSUARIO BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDUSUARIO)
REFERENCES USUARIO(IDUSUARIO),
IDTAREA BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDTAREA)
REFERENCES TAREA(IDTAREA)
);

CREATE TABLE PERFIL(
IDUSUARIO BIGINT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY(IDUSUARIO)
REFERENCES USUARIO(IDUSUARIO),
FECHANACIMIENTO DATE
);